### ISSUE TITLE
From clean install, npm run debug:android with Nativescript 5.4 throws error

### ISSUE THREAD

**Issue by kurtaschliman** [nativescript-vue/vue-cli-plugin-nativescript-vue#15]
I'm not entirely sure if this is fully specific to this plugin, but this does not occur when creating a new project using the [Nativescript-vue/vue-cli-template](https://github.com/nativescript-vue/vue-cli-template). 

The problematic line of code is [here in the tns-core-modules](https://github.com/NativeScript/NativeScript/blob/e7c575e96e4dc2a44c27181068d5bbb31082ce13/tns-core-modules/debugger/devtools-elements.common.ts#L5)

It seems that between Typescript and webpack `utils_1.mainThreadify` cannot be found.

Any help or direction is appreciated.

```
tns --version: 5.4.0
node -v: v10.13.0
npm -v: 6.4.1
OS: Windows 10
@vue/cli: V3.7.0
```

Steps to reproduce: 
```
vue create ns-vue-cli-3
- Vuex
- Vue Router
- Typescript w/ Babel
- Class Based Components
- SCSS (Dart)
cd ns-vue-cli-3
vue add vue-cli-plugin-nativescript-vue
- Router History Mode
- New App
Edit package.json tns-android to 5.4.0
tns platform remove android // just for good measure
npm run debug:android
``` 

#### Output from Emulator: (Android version: 8.0 (Oreo) - API 26)
(sorry for the long log dump, tried putting this in a `<details>` block but couldn't fully get the formatting to work)
```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

TypeError: utils_1.mainThreadify is not a function
File: "file:///data/data/org.nativescript.application/files/app/vendor.js, line: 18502, column: 29

StackTrace: 
	Frame: function:'../node_modules/tns-core-modules/debugger/devtools-elements.common.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 18502, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/debugger/devtools-elements.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 18554, column: 34
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 39201, column: 18
	Frame: function:'../node_modules/tns-core-modules/ui/frame/frame.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 40462, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55211, column: 13
	Frame: function:'../node_modules/tns-core-modules/utils/mainthread-helper.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55243, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/utils/utils-common.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55484, column: 27
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/utils/utils.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55710, column: 10
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 268, column: 13
	Frame: function:'../node_modules/nativescript-vue/dist/index.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 13906, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 693, column: 120
	Frame: function:'./main.ts', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 728, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'0', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 921, column: 18
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266
TypeError: utils_1.mainThreadify is not a function
File: "<unknown>, line: 1, column: 265
StackTrace: 
	Frame: function:'../node_modules/tns-core-modules/debugger/devtools-elements.common.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 18502, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/debugger/devtools-elements.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 18554, column: 34
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 39201, column: 18
	Frame: function:'../node_modules/tns-core-modules/ui/frame/frame.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 40462, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55211, column: 13
	Frame: function:'../node_modules/tns-core-modules/utils/mainthread-helper.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55243, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/utils/utils-common.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55484, column: 27
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/utils/utils.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55710, column: 10
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 268, column: 13
	Frame: function:'../node_modules/nativescript-vue/dist/index.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 13906, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 693, column: 120
	Frame: function:'./main.ts', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 728, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'0', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 921, column: 18
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: utils_1.mainThreadify is not a function
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'../node_modules/tns-core-modules/debugger/devtools-elements.common.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 18502, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/debugger/devtools-elements.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 18554, column: 34
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 39201, column: 18
	Frame: function:'../node_modules/tns-core-modules/ui/frame/frame.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 40462, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55211, column: 13
	Frame: function:'../node_modules/tns-core-modules/utils/mainthread-helper.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55243, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/utils/utils-common.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55484, column: 27
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/utils/utils.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55710, column: 10
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 268, column: 13
	Frame: function:'../node_modules/nativescript-vue/dist/index.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 13906, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 693, column: 120
	Frame: function:'./main.ts', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 728, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'0', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 921, column: 18
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266

at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

TypeError: utils_1.mainThreadify is not a function
File: "file:///data/data/org.nativescript.application/files/app/vendor.js, line: 18502, column: 29

StackTrace: 
	Frame: function:'../node_modules/tns-core-modules/debugger/devtools-elements.common.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 18502, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/debugger/devtools-elements.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 18554, column: 34
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 39201, column: 18
	Frame: function:'../node_modules/tns-core-modules/ui/frame/frame.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 40462, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55211, column: 13
	Frame: function:'../node_modules/tns-core-modules/utils/mainthread-helper.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55243, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/utils/utils-common.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55484, column: 27
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/utils/utils.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55710, column: 10
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 268, column: 13
	Frame: function:'../node_modules/nativescript-vue/dist/index.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 13906, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 693, column: 120
	Frame: function:'./main.ts', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 728, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'0', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 921, column: 18
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: utils_1.mainThreadify is not a function
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'../node_modules/tns-core-modules/debugger/devtools-elements.common.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 18502, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/debugger/devtools-elements.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 18554, column: 34
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 39201, column: 18
	Frame: function:'../node_modules/tns-core-modules/ui/frame/frame.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 40462, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55211, column: 13
	Frame: function:'../node_modules/tns-core-modules/utils/mainthread-helper.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55243, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/utils/utils-common.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55484, column: 27
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/utils/utils.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55710, column: 10
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 268, column: 13
	Frame: function:'../node_modules/nativescript-vue/dist/index.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 13906, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 693, column: 120
	Frame: function:'./main.ts', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 728, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'0', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 921, column: 18
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: utils_1.mainThreadify is not a function
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'../node_modules/tns-core-modules/debugger/devtools-elements.common.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 18502, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/debugger/devtools-elements.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 18554, column: 34
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 39201, column: 18
	Frame: function:'../node_modules/tns-core-modules/ui/frame/frame.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 40462, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55211, column: 13
	Frame: function:'../node_modules/tns-core-modules/utils/mainthread-helper.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55243, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/utils/utils-common.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55484, column: 27
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'../node_modules/tns-core-modules/utils/utils.android.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 55710, column: 10
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 268, column: 13
	Frame: function:'../node_modules/nativescript-vue/dist/index.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 13906, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 693, column: 120
	Frame: function:'./main.ts', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 728, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'0', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 921, column: 18
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
Frame: function:'require', file:'', line: 1, column: 266
at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:624)
at com.tns.Runtime.run(Runtime.java:616)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
... 8 more
```

**Comment by jawa-the-hutt** [comment]
I've added a commit to the `dev` branch that may or may not address this.  The reason I'm not sure is because the commit wasn't geared towards solving your issue but rather it was geared towards getting HMR working.  It also includes updates to dependencies and some other webpack related config updates.

However, I've tried reproducing your issue and I cannot reproduce it so I don't know if what's currently in `dev` will fix this or not.  So, I need your help testing it out to see.

Create a new vue project as normal and then install and invoke the plugin in the dev branch like this to test it out:
`npm install git+https://github.com/nativescript-vue/vue-cli-plugin-nativescript-vue/tree/dev`
`npm invoke vue-cli-plugin-nativescript-vue`

**Comment by jawa-the-hutt** [comment]
sorry...wrong install link.  here's the correct one for the `dev` branch:
`npm install git+https://github.com/nativescript-vue/vue-cli-plugin-nativescript-vue.git#dev `

**Comment by kurtaschliman** [comment]
Thanks for the update @jawa-the-hutt ! Did you mean the `dev` branch or just to `master`? Seems that there is not a `dev` branch here on Github.

**Comment by jawa-the-hutt** [comment]
The `dev` branch changes that were mentioned are now rolled into master and the npm package is updated with them, so you should be able to just update via npm and test it out to see if it fixed your issue.
