### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by paperscissors** [nativescript-vue/vue-cli-plugin-nativescript-vue#33]
Trying to install via Vue-CLI 3.4.0 and version 0.2.1 of this plugin.

I've tried both via command line and also via `vue ui`, and get this error:

```
{"type":"warning","data":"../../../package.json: No license field"}
 ERROR  TypeError: Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1233:7)
    at api.render (/Users/tomfilepp/work/FSU-Rebuild/games/node_modules/vue-cli-plugin-nativescript-vue/generator/index.js:221:14)
    at Generator.resolveFiles (/Users/tomfilepp/.nvm/versions/node/v8.15.0/lib/node_modules/@vue/cli/lib/Generator.js:202:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
{ Error: Command failed: vue invoke vue-cli-plugin-nativescript-vue --$inlineOptions {"applicationId":"org.fsu.adhd","historyMode":false,"isNewProject":true,"isNativeOnly":fal
se,"templateType":"nvw"}
adding to package.json
deleting from package.json
doing template rendering

🚀  Invoking generator for vue-cli-plugin-nativescript-vue...

    at makeError (/Users/tomfilepp/.nvm/versions/node/v8.15.0/lib/node_modules/@vue/cli/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/tomfilepp/.nvm/versions/node/v8.15.0/lib/node_modules/@vue/cli/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  code: 1,
  stdout: 'adding to package.json\ndeleting from package.json\ndoing template rendering\n\n🚀  Invoking generator for vue-cli-plugin-nativescript-vue...\n',
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'vue invoke vue-cli-plugin-nativescript-vue --$inlineOptions {"applicationId":"org.fsu.adhd","historyMode":false,"isNewProject":true,"isNativeOnly":false,"templateType":"nvw"}',
  timedOut: false,
  killed: false }
```

**Comment by paperscissors** [comment]
By the way, I did try upgrading to Vue-CLI 4.* and it throws a whole other set of errors, #31 #2
